# CMake generated Testfile for 
# Source directory: C:/spiral/spiral-software/tests/Advanced
# Build directory: C:/spiral/spiral-software/tests/Advanced
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(Hockney "C:/spiral/spiral-software/spiral.bat" "<" "C:\\spiral\\spiral-software\\tests\\Advanced\\Hockney.g")
  set_tests_properties(Hockney PROPERTIES  FAIL_REGULAR_EXPRESSION "TEST FAILED" LABELS "Advanced" _BACKTRACE_TRIPLES "C:/spiral/spiral-software/config/CMakeIncludes/TestDefines.cmake;37;add_test;C:/spiral/spiral-software/tests/Advanced/CMakeLists.txt;23;my_add_test_target;C:/spiral/spiral-software/tests/Advanced/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(Hockney "C:/spiral/spiral-software/spiral.bat" "<" "C:\\spiral\\spiral-software\\tests\\Advanced\\Hockney.g")
  set_tests_properties(Hockney PROPERTIES  FAIL_REGULAR_EXPRESSION "TEST FAILED" LABELS "Advanced" _BACKTRACE_TRIPLES "C:/spiral/spiral-software/config/CMakeIncludes/TestDefines.cmake;37;add_test;C:/spiral/spiral-software/tests/Advanced/CMakeLists.txt;23;my_add_test_target;C:/spiral/spiral-software/tests/Advanced/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(Hockney "C:/spiral/spiral-software/spiral.bat" "<" "C:\\spiral\\spiral-software\\tests\\Advanced\\Hockney.g")
  set_tests_properties(Hockney PROPERTIES  FAIL_REGULAR_EXPRESSION "TEST FAILED" LABELS "Advanced" _BACKTRACE_TRIPLES "C:/spiral/spiral-software/config/CMakeIncludes/TestDefines.cmake;37;add_test;C:/spiral/spiral-software/tests/Advanced/CMakeLists.txt;23;my_add_test_target;C:/spiral/spiral-software/tests/Advanced/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(Hockney "C:/spiral/spiral-software/spiral.bat" "<" "C:\\spiral\\spiral-software\\tests\\Advanced\\Hockney.g")
  set_tests_properties(Hockney PROPERTIES  FAIL_REGULAR_EXPRESSION "TEST FAILED" LABELS "Advanced" _BACKTRACE_TRIPLES "C:/spiral/spiral-software/config/CMakeIncludes/TestDefines.cmake;37;add_test;C:/spiral/spiral-software/tests/Advanced/CMakeLists.txt;23;my_add_test_target;C:/spiral/spiral-software/tests/Advanced/CMakeLists.txt;0;")
else()
  add_test(Hockney NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(Planewave-3D-FFT "C:/spiral/spiral-software/spiral.bat" "<" "C:\\spiral\\spiral-software\\tests\\Advanced\\Planewave-3D-FFT.g")
  set_tests_properties(Planewave-3D-FFT PROPERTIES  FAIL_REGULAR_EXPRESSION "TEST FAILED" LABELS "Advanced" _BACKTRACE_TRIPLES "C:/spiral/spiral-software/config/CMakeIncludes/TestDefines.cmake;37;add_test;C:/spiral/spiral-software/tests/Advanced/CMakeLists.txt;23;my_add_test_target;C:/spiral/spiral-software/tests/Advanced/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(Planewave-3D-FFT "C:/spiral/spiral-software/spiral.bat" "<" "C:\\spiral\\spiral-software\\tests\\Advanced\\Planewave-3D-FFT.g")
  set_tests_properties(Planewave-3D-FFT PROPERTIES  FAIL_REGULAR_EXPRESSION "TEST FAILED" LABELS "Advanced" _BACKTRACE_TRIPLES "C:/spiral/spiral-software/config/CMakeIncludes/TestDefines.cmake;37;add_test;C:/spiral/spiral-software/tests/Advanced/CMakeLists.txt;23;my_add_test_target;C:/spiral/spiral-software/tests/Advanced/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(Planewave-3D-FFT "C:/spiral/spiral-software/spiral.bat" "<" "C:\\spiral\\spiral-software\\tests\\Advanced\\Planewave-3D-FFT.g")
  set_tests_properties(Planewave-3D-FFT PROPERTIES  FAIL_REGULAR_EXPRESSION "TEST FAILED" LABELS "Advanced" _BACKTRACE_TRIPLES "C:/spiral/spiral-software/config/CMakeIncludes/TestDefines.cmake;37;add_test;C:/spiral/spiral-software/tests/Advanced/CMakeLists.txt;23;my_add_test_target;C:/spiral/spiral-software/tests/Advanced/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(Planewave-3D-FFT "C:/spiral/spiral-software/spiral.bat" "<" "C:\\spiral\\spiral-software\\tests\\Advanced\\Planewave-3D-FFT.g")
  set_tests_properties(Planewave-3D-FFT PROPERTIES  FAIL_REGULAR_EXPRESSION "TEST FAILED" LABELS "Advanced" _BACKTRACE_TRIPLES "C:/spiral/spiral-software/config/CMakeIncludes/TestDefines.cmake;37;add_test;C:/spiral/spiral-software/tests/Advanced/CMakeLists.txt;23;my_add_test_target;C:/spiral/spiral-software/tests/Advanced/CMakeLists.txt;0;")
else()
  add_test(Planewave-3D-FFT NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(WarpX-1D "C:/spiral/spiral-software/spiral.bat" "<" "C:\\spiral\\spiral-software\\tests\\Advanced\\WarpX-1D.g")
  set_tests_properties(WarpX-1D PROPERTIES  FAIL_REGULAR_EXPRESSION "TEST FAILED" LABELS "Advanced" _BACKTRACE_TRIPLES "C:/spiral/spiral-software/config/CMakeIncludes/TestDefines.cmake;37;add_test;C:/spiral/spiral-software/tests/Advanced/CMakeLists.txt;23;my_add_test_target;C:/spiral/spiral-software/tests/Advanced/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(WarpX-1D "C:/spiral/spiral-software/spiral.bat" "<" "C:\\spiral\\spiral-software\\tests\\Advanced\\WarpX-1D.g")
  set_tests_properties(WarpX-1D PROPERTIES  FAIL_REGULAR_EXPRESSION "TEST FAILED" LABELS "Advanced" _BACKTRACE_TRIPLES "C:/spiral/spiral-software/config/CMakeIncludes/TestDefines.cmake;37;add_test;C:/spiral/spiral-software/tests/Advanced/CMakeLists.txt;23;my_add_test_target;C:/spiral/spiral-software/tests/Advanced/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(WarpX-1D "C:/spiral/spiral-software/spiral.bat" "<" "C:\\spiral\\spiral-software\\tests\\Advanced\\WarpX-1D.g")
  set_tests_properties(WarpX-1D PROPERTIES  FAIL_REGULAR_EXPRESSION "TEST FAILED" LABELS "Advanced" _BACKTRACE_TRIPLES "C:/spiral/spiral-software/config/CMakeIncludes/TestDefines.cmake;37;add_test;C:/spiral/spiral-software/tests/Advanced/CMakeLists.txt;23;my_add_test_target;C:/spiral/spiral-software/tests/Advanced/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(WarpX-1D "C:/spiral/spiral-software/spiral.bat" "<" "C:\\spiral\\spiral-software\\tests\\Advanced\\WarpX-1D.g")
  set_tests_properties(WarpX-1D PROPERTIES  FAIL_REGULAR_EXPRESSION "TEST FAILED" LABELS "Advanced" _BACKTRACE_TRIPLES "C:/spiral/spiral-software/config/CMakeIncludes/TestDefines.cmake;37;add_test;C:/spiral/spiral-software/tests/Advanced/CMakeLists.txt;23;my_add_test_target;C:/spiral/spiral-software/tests/Advanced/CMakeLists.txt;0;")
else()
  add_test(WarpX-1D NOT_AVAILABLE)
endif()
