# CMake generated Testfile for 
# Source directory: C:/spiral/spiral-software/tests/Basic
# Build directory: C:/spiral/spiral-software/tests/Basic
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(basic_test "C:/spiral/spiral-software/spiral.bat" "<" "C:\\spiral\\spiral-software\\tests\\Basic\\basic_test.g")
  set_tests_properties(basic_test PROPERTIES  FAIL_REGULAR_EXPRESSION "TEST FAILED" LABELS "Basic" _BACKTRACE_TRIPLES "C:/spiral/spiral-software/config/CMakeIncludes/TestDefines.cmake;37;add_test;C:/spiral/spiral-software/tests/Basic/CMakeLists.txt;23;my_add_test_target;C:/spiral/spiral-software/tests/Basic/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(basic_test "C:/spiral/spiral-software/spiral.bat" "<" "C:\\spiral\\spiral-software\\tests\\Basic\\basic_test.g")
  set_tests_properties(basic_test PROPERTIES  FAIL_REGULAR_EXPRESSION "TEST FAILED" LABELS "Basic" _BACKTRACE_TRIPLES "C:/spiral/spiral-software/config/CMakeIncludes/TestDefines.cmake;37;add_test;C:/spiral/spiral-software/tests/Basic/CMakeLists.txt;23;my_add_test_target;C:/spiral/spiral-software/tests/Basic/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(basic_test "C:/spiral/spiral-software/spiral.bat" "<" "C:\\spiral\\spiral-software\\tests\\Basic\\basic_test.g")
  set_tests_properties(basic_test PROPERTIES  FAIL_REGULAR_EXPRESSION "TEST FAILED" LABELS "Basic" _BACKTRACE_TRIPLES "C:/spiral/spiral-software/config/CMakeIncludes/TestDefines.cmake;37;add_test;C:/spiral/spiral-software/tests/Basic/CMakeLists.txt;23;my_add_test_target;C:/spiral/spiral-software/tests/Basic/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(basic_test "C:/spiral/spiral-software/spiral.bat" "<" "C:\\spiral\\spiral-software\\tests\\Basic\\basic_test.g")
  set_tests_properties(basic_test PROPERTIES  FAIL_REGULAR_EXPRESSION "TEST FAILED" LABELS "Basic" _BACKTRACE_TRIPLES "C:/spiral/spiral-software/config/CMakeIncludes/TestDefines.cmake;37;add_test;C:/spiral/spiral-software/tests/Basic/CMakeLists.txt;23;my_add_test_target;C:/spiral/spiral-software/tests/Basic/CMakeLists.txt;0;")
else()
  add_test(basic_test NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(break-me "C:/spiral/spiral-software/spiral.bat" "<" "C:\\spiral\\spiral-software\\tests\\Basic\\break-me.g")
  set_tests_properties(break-me PROPERTIES  FAIL_REGULAR_EXPRESSION "TEST FAILED" LABELS "Basic" _BACKTRACE_TRIPLES "C:/spiral/spiral-software/config/CMakeIncludes/TestDefines.cmake;37;add_test;C:/spiral/spiral-software/tests/Basic/CMakeLists.txt;23;my_add_test_target;C:/spiral/spiral-software/tests/Basic/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(break-me "C:/spiral/spiral-software/spiral.bat" "<" "C:\\spiral\\spiral-software\\tests\\Basic\\break-me.g")
  set_tests_properties(break-me PROPERTIES  FAIL_REGULAR_EXPRESSION "TEST FAILED" LABELS "Basic" _BACKTRACE_TRIPLES "C:/spiral/spiral-software/config/CMakeIncludes/TestDefines.cmake;37;add_test;C:/spiral/spiral-software/tests/Basic/CMakeLists.txt;23;my_add_test_target;C:/spiral/spiral-software/tests/Basic/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(break-me "C:/spiral/spiral-software/spiral.bat" "<" "C:\\spiral\\spiral-software\\tests\\Basic\\break-me.g")
  set_tests_properties(break-me PROPERTIES  FAIL_REGULAR_EXPRESSION "TEST FAILED" LABELS "Basic" _BACKTRACE_TRIPLES "C:/spiral/spiral-software/config/CMakeIncludes/TestDefines.cmake;37;add_test;C:/spiral/spiral-software/tests/Basic/CMakeLists.txt;23;my_add_test_target;C:/spiral/spiral-software/tests/Basic/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(break-me "C:/spiral/spiral-software/spiral.bat" "<" "C:\\spiral\\spiral-software\\tests\\Basic\\break-me.g")
  set_tests_properties(break-me PROPERTIES  FAIL_REGULAR_EXPRESSION "TEST FAILED" LABELS "Basic" _BACKTRACE_TRIPLES "C:/spiral/spiral-software/config/CMakeIncludes/TestDefines.cmake;37;add_test;C:/spiral/spiral-software/tests/Basic/CMakeLists.txt;23;my_add_test_target;C:/spiral/spiral-software/tests/Basic/CMakeLists.txt;0;")
else()
  add_test(break-me NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(integers_test "C:/spiral/spiral-software/spiral.bat" "<" "C:\\spiral\\spiral-software\\tests\\Basic\\integers_test.g")
  set_tests_properties(integers_test PROPERTIES  FAIL_REGULAR_EXPRESSION "TEST FAILED" LABELS "Basic" _BACKTRACE_TRIPLES "C:/spiral/spiral-software/config/CMakeIncludes/TestDefines.cmake;37;add_test;C:/spiral/spiral-software/tests/Basic/CMakeLists.txt;23;my_add_test_target;C:/spiral/spiral-software/tests/Basic/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(integers_test "C:/spiral/spiral-software/spiral.bat" "<" "C:\\spiral\\spiral-software\\tests\\Basic\\integers_test.g")
  set_tests_properties(integers_test PROPERTIES  FAIL_REGULAR_EXPRESSION "TEST FAILED" LABELS "Basic" _BACKTRACE_TRIPLES "C:/spiral/spiral-software/config/CMakeIncludes/TestDefines.cmake;37;add_test;C:/spiral/spiral-software/tests/Basic/CMakeLists.txt;23;my_add_test_target;C:/spiral/spiral-software/tests/Basic/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(integers_test "C:/spiral/spiral-software/spiral.bat" "<" "C:\\spiral\\spiral-software\\tests\\Basic\\integers_test.g")
  set_tests_properties(integers_test PROPERTIES  FAIL_REGULAR_EXPRESSION "TEST FAILED" LABELS "Basic" _BACKTRACE_TRIPLES "C:/spiral/spiral-software/config/CMakeIncludes/TestDefines.cmake;37;add_test;C:/spiral/spiral-software/tests/Basic/CMakeLists.txt;23;my_add_test_target;C:/spiral/spiral-software/tests/Basic/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(integers_test "C:/spiral/spiral-software/spiral.bat" "<" "C:\\spiral\\spiral-software\\tests\\Basic\\integers_test.g")
  set_tests_properties(integers_test PROPERTIES  FAIL_REGULAR_EXPRESSION "TEST FAILED" LABELS "Basic" _BACKTRACE_TRIPLES "C:/spiral/spiral-software/config/CMakeIncludes/TestDefines.cmake;37;add_test;C:/spiral/spiral-software/tests/Basic/CMakeLists.txt;23;my_add_test_target;C:/spiral/spiral-software/tests/Basic/CMakeLists.txt;0;")
else()
  add_test(integers_test NOT_AVAILABLE)
endif()
